/************************************************************************
 *
 *			ＰＣ−ＳＥＲＶＥ
 *
 *		名称		: PCSERVE 関数ヘッダ
 *		ファイル名	: pcsfunc.h
 *		作成者		: s.aizawa
 *
 ************************************************************************/

#define	PSENTRY

extern	PCCB	PSENTRY PSConnect(SHORT, FPCHAR, FPCHAR, FPSHORT);
extern	SHORT	PSENTRY PSDisconnect(PCCB);
//extern	SHORT	PSENTRY PSLogin(PCCB, CHAR *, CHAR *);
extern	SHORT	PSENTRY PSGetErrCode(PCCB);
extern	char	*PSENTRY PSGetErrorText(SHORT nErrorCode);
//extern	SHORT	PSENTRY PSGetTime(PCCB, PSTIME);

/*	データベース操作関数	*/
extern	PFCB	PSENTRY PSDBOpen(PCCB, FPCHAR);
extern	PFCB	PSENTRY PSDBCreate(PCCB, FPCHAR, PDBF_I, SHORT);
extern	VOID	PSENTRY PSDBClose(PFCB);
extern	VOID	PSENTRY PSDBCloseAll(PCCB);
extern	VOID	PSENTRY PSDBFlush(PFCB);
extern	VOID	PSENTRY PSDBFlushAll(PCCB);
extern	SHORT	PSENTRY PSDBIndex(PFCB, FPCHAR);
extern	SHORT	PSENTRY PSDBIdxCreate(PFCB, FPCHAR, FPCHAR, SHORT);
extern	VOID	PSENTRY PSDBChgIdx(PFCB, SHORT);
extern	VOID	PSENTRY PSDBSearch(PFCB, FPCHAR, SHORT);
extern	SHORT	PSENTRY PSDBSearch2(PFCB, FPCHAR, SHORT);
extern	LONG	PSENTRY PSDBSearchLock(PFCB, FPCHAR, SHORT);
extern	LONG	PSENTRY PSDBCount(PFCB, FPCHAR, SHORT);
extern	VOID	PSENTRY PSDBStore(PFCB, FPCHAR);
extern	VOID	PSENTRY PSDBStoreUniq(PFCB, FPCHAR);
extern	VOID	PSENTRY PSDBUpdate(PFCB, FPCHAR);
extern	VOID	PSENTRY PSDBUpdateKey(PFCB, FPCHAR, SHORT, FPCHAR);
extern	VOID	PSENTRY PSDBDelete(PFCB);
extern	VOID	PSENTRY PSDBRecall(PFCB);
extern	VOID	PSENTRY PSDBDelete2(PFCB);
extern	VOID	PSENTRY PSDBDelete3(PFCB);
extern	VOID	PSENTRY PSDBDeleteKey(PFCB, FPCHAR, SHORT, SHORT);
extern	VOID	PSENTRY PSDBTop(PFCB);
extern	VOID	PSENTRY PSDBBottom(PFCB);
extern	VOID	PSENTRY PSDBSet(PFCB, LONG);
extern	VOID	PSENTRY PSDBSkip(PFCB, LONG);
extern	VOID	PSENTRY PSDBReindex(PFCB);
extern	VOID	PSENTRY PSDBPack(PFCB);
extern	VOID	PSENTRY PSDBRead(PFCB, FPCHAR);
extern	SHORT	PSENTRY PSDBReadNext(PFCB, SHORT, FPCHAR);
extern	SHORT	PSENTRY PSDBReadBack(PFCB, SHORT, FPCHAR);
extern	SHORT	PSENTRY PSDBReadKey(PFCB, FPCHAR, SHORT, FPCHAR, SHORT);
extern	VOID	PSENTRY PSDBClrRecord(PFCB);
extern	VOID	PSENTRY PSDBGetRecord(PFCB);
extern	SHORT	PSENTRY PSDBGetField(PFCB, FPCHAR, FPVOID);
extern	VOID	PSENTRY PSDBSetField(PFCB, FPCHAR, FPVOID);
extern	VOID	PSENTRY PSDBAddRecord(PFCB);
extern	VOID	PSENTRY PSDBUpdRecord(PFCB);
extern	VOID	PSENTRY PSDBCopy(PFCB, PFCB);
extern	SHORT	PSENTRY PSDBCheckDeleted(PFCB);
extern	VOID	PSENTRY PSDBSetFilter(PFCB, FPCHAR);
extern	LONG	PSENTRY PSDBSelect(PFCB, FPCHAR);
extern	VOID	PSENTRY PSDBSetDeleted(PFCB, SHORT);
extern	LONG	PSENTRY PSDBLRecNo(PFCB);
extern	LONG	PSENTRY PSDBLRecCount(PFCB);
extern	VOID	PSENTRY PSDBLSet(PFCB, LONG);
extern	VOID	PSENTRY PSDBZip(PFCB);
extern	SHORT	PSENTRY PSDBCheckUpdate(PFCB);
extern	VOID	PSENTRY PSDBLock(PFCB, SHORT);
extern	VOID	PSENTRY PSDBUnlock(PFCB, SHORT);
extern	LONG	PSENTRY PSDBRecCount(PFCB);
extern	SHORT	PSENTRY PSDBBof(PFCB);
extern	VOID	PSENTRY PSDBDbf(PFCB, FPCHAR);
extern	SHORT	PSENTRY PSDBEof(PFCB);
extern	SHORT	PSENTRY PSDBNField(PFCB);
extern	VOID	PSENTRY PSDBField(PFCB, SHORT, PDBF_I);
extern	VOID	PSENTRY PSDBNdx(PFCB, SHORT, FPCHAR);
extern	LONG	PSENTRY PSDBRecNo(PFCB);
extern	SHORT	PSENTRY PSDBRecSize(PFCB);
extern	SHORT	PSENTRY PSDBGetErrCode(PFCB);
extern	VOID	PSENTRY PSDBSetErrHandler(PCCB, VOID (*)(PFCB, SHORT));
extern	VOID	PSENTRY	PSDBAsync(PCCB);
extern	SHORT	PSENTRY PSDBSetReadField(PFCB, FPCHAR);
extern	SHORT	PSENTRY PSDBReadVB(PFCB, SHORT, SHORT, FPVOID);
extern	VOID	PSENTRY	PSDBSetScramble(PFCB);
extern	VOID	PSENTRY PSDBUpdateOracle(PFCB, FPCHAR, FPCHAR);
extern	VOID	PSENTRY PSDBDeleteOracle(PFCB, FPCHAR);
extern	VOID	PSENTRY	PSDBSetPassword(PFCB, FPCHAR);
extern	SHORT	PSENTRY PSDBReadAll(PFCB, FPCHAR);
extern	VOID	PSENTRY	PSDBPackIndex(PCCB, FPCHAR);
extern	LONG	PSENTRY	PSDBReadBinary(PFCB, CHAR *, FPCHAR, LONG);
extern	VOID	PSENTRY	PSDBWriteBinary(PFCB, CHAR *, CHAR *, LONG);
extern	LONG	PSENTRY	PSDBGetBinarySize(PFCB, CHAR *);
